import { Inter } from 'next/font/google'
import Footer from './components/footer/page'
import Navbar from './components/navbar/page'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BlogSite',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Footer/>
        {children}
        </body>
    </html>
  )
}
